backend:
  name: github
  repo: GabiSystem/FilhosDeAndarilhoDK # seu repositório
  branch: main
  auth_scope: repo
  app_id: Ov23liy7QFFywAsw7jvc # seu Client ID do OAuth App
  base_url: https://oauth-proxy.decapcms.org
  site_domain: gabisystem.github.io

media_folder: "pages/articles/assets/img"
public_folder: "/pages/articles/assets/img"

collections:
  - name: "artigos"
    label: "Artigos"
    folder: "pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Imagem de Capa", name: "thumbnail", widget: "image" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
